package app.followlens.diff

import com.fleeksoft.ksoup.Ksoup
import com.fleeksoft.ksoup.nodes.Element
import kotlinx.datetime.LocalDateTime
import kotlinx.datetime.TimeZone
import kotlinx.datetime.toInstant
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.longOrNull

/**
 * Parses the files from Instagram's "Download your information" export — both the JSON and the
 * HTML format are accepted, auto-detected from content (not file extension).
 *
 * Layout inside the ZIP: `connections/followers_and_following/`
 *   - `followers_1.json` (and `_2`, ...) — a TOP-LEVEL JSON ARRAY of entries
 *   - `following.json` — an OBJECT with key `relationships_following` -> array of entries
 *
 * Each entry, in `followers_1.json`:
 * ```
 * { "title": "", "string_list_data": [
 *     { "href": "https://www.instagram.com/USERNAME", "value": "USERNAME", "timestamp": 1700000000 }
 * ]}
 * ```
 * `following.json` entries carry the username differently — `string_list_data[0]` has no `value`,
 * `href` is shaped `.../_u/USERNAME`, and the username is instead the entry's own `title`:
 * ```
 * { "title": "USERNAME", "string_list_data": [
 *     { "href": "https://www.instagram.com/_u/USERNAME", "timestamp": 1700000000 }
 * ]}
 * ```
 * [collectEntries] tries `value`, then `title`, then parses `href` as a last resort, so both
 * shapes (and any file that mixes them) work.
 *
 * The HTML export shows the same asymmetry: `following.html` renders each entry as username,
 * blank line, the `_u/`-prefixed profile URL, then a date (`"Sep 17, 2026 11:21 am"`); the
 * `followers_N.html` files render only username then date — no visible URL line at all, though
 * the username is still an `<a href="https://www.instagram.com/USERNAME">` link. [collectHtmlEntries]
 * doesn't rely on either shape specifically: it selects every anchor linking to instagram.com
 * anywhere in the document (so it doesn't care which of the two shapes it's looking at) and reads
 * the username from the `href` attribute, not the visible text or line position.
 *
 * The caller is responsible for unzipping and locating the files (platform-specific). This class
 * only turns raw export text into [Account] sets.
 */
class ExportParser {

    // Kept private so core-diff's choice of JSON library stays out of its public API.
    private val json: Json = Json { ignoreUnknownKeys = true; isLenient = true }

    class ParseException(message: String) : Exception(message)

    /** Which side of the export a file looks like — used to catch a file dropped in the wrong slot. */
    enum class ExportKind { FOLLOWING, FOLLOWERS, UNKNOWN }

    /**
     * Best-effort detection of whether [content] is a followers or a following export, so the
     * upload UI can flag a file dropped in the wrong slot. JSON has a confident signal (the
     * `relationships_following`/`relationships_followers` key, or a bare array — followers files
     * are never wrapped in an object in practice). HTML's confident signal is the literal
     * "Followers"/"Following" header line Instagram prints first, right before "Generated by ...
     * UTC." (confirmed against a real export); if that's missing or unrecognized, falls back to
     * the lower-confidence `_u/`-href-prefix majority. Returns [ExportKind.UNKNOWN] rather than
     * guessing when neither signal is conclusive.
     */
    fun detectKind(content: String): ExportKind {
        if (content.isBlank()) return ExportKind.UNKNOWN
        return if (looksLikeHtml(content)) detectHtmlKind(content) else detectJsonKind(content)
    }

    private fun detectJsonKind(content: String): ExportKind {
        val root = try {
            json.parseToJsonElement(content)
        } catch (e: Exception) {
            return ExportKind.UNKNOWN
        }
        return when (root) {
            is JsonObject -> when {
                root.containsKey("relationships_following") -> ExportKind.FOLLOWING
                root.containsKey("relationships_followers") -> ExportKind.FOLLOWERS
                else -> ExportKind.UNKNOWN
            }
            is JsonArray -> ExportKind.FOLLOWERS
            else -> ExportKind.UNKNOWN
        }
    }

    private fun detectHtmlKind(content: String): ExportKind {
        val doc = try {
            Ksoup.parse(html = content)
        } catch (e: Exception) {
            return ExportKind.UNKNOWN
        }
        val header = htmlHeaderRegex.find(doc.text().trim())
        if (header != null) {
            return if (header.groupValues[1] == "Following") ExportKind.FOLLOWING else ExportKind.FOLLOWERS
        }
        val anchors = doc.select("a[href*=instagram.com]")
        if (anchors.isEmpty()) return ExportKind.UNKNOWN
        val uPrefixRatio = anchors.count { it.attr("href").contains("/_u/") }.toDouble() / anchors.size
        return when {
            uPrefixRatio >= 0.8 -> ExportKind.FOLLOWING
            uPrefixRatio <= 0.2 -> ExportKind.FOLLOWERS
            else -> ExportKind.UNKNOWN
        }
    }

    /**
     * Parse one or more `followers_N.json` files. Pass every part; they are merged.
     * Accepts either a bare array (the normal shape) or an object wrapping
     * `relationships_followers` (seen in some exports).
     */
    fun parseFollowers(vararg followerFileContents: String): Set<Account> {
        if (followerFileContents.isEmpty()) throw ParseException("no followers file provided")
        val out = LinkedHashMap<String, Account>()
        followerFileContents.forEachIndexed { i, content ->
            if (content.isBlank()) throw ParseException("followers file #${i + 1} is empty")
            if (looksLikeHtml(content)) {
                collectHtmlEntries(content, out)
            } else {
                val root = parseRoot(content, "followers file #${i + 1}")
                val entries = when (root) {
                    is JsonArray -> root
                    is JsonObject -> root["relationships_followers"]?.jsonArray
                        ?: throw ParseException("followers file #${i + 1}: object without 'relationships_followers'")
                    else -> throw ParseException("followers file #${i + 1}: unexpected top-level JSON")
                }
                collectEntries(entries, out)
            }
        }
        return out.values.toSet()
    }

    /**
     * Parse `following.json` or `following.html`. Accepts the standard `relationships_following`
     * wrapper, a bare array, or the HTML export.
     */
    fun parseFollowing(followingFileContent: String): Set<Account> {
        if (followingFileContent.isBlank()) throw ParseException("following file is empty")
        val out = LinkedHashMap<String, Account>()
        if (looksLikeHtml(followingFileContent)) {
            collectHtmlEntries(followingFileContent, out)
        } else {
            val root = parseRoot(followingFileContent, "following file")
            val entries = when (root) {
                is JsonArray -> root
                is JsonObject -> root["relationships_following"]?.jsonArray
                    ?: throw ParseException("following file: object without 'relationships_following'")
                else -> throw ParseException("following file: unexpected top-level JSON")
            }
            collectEntries(entries, out)
        }
        return out.values.toSet()
    }

    fun parseSnapshot(followingFileContent: String, vararg followerFileContents: String): ExportSnapshot =
        ExportSnapshot(
            followers = parseFollowers(*followerFileContents),
            following = parseFollowing(followingFileContent),
        )

    private fun parseRoot(content: String, label: String): JsonElement {
        return try {
            json.parseToJsonElement(content)
        } catch (e: Exception) {
            throw ParseException("$label is not valid JSON: ${e.message}")
        }
    }

    private fun collectEntries(entries: JsonArray, out: MutableMap<String, Account>) {
        for (entry in entries) {
            val entryObject = entry.jsonObject
            val sld = entryObject["string_list_data"]?.jsonArray ?: continue
            val first = sld.firstOrNull()?.jsonObject ?: continue

            // followers_1.json puts the username in string_list_data[0].value. following.json
            // (as of the 2026 export format) omits "value" entirely and puts it in the entry's
            // own "title" instead, with href shaped ".../_u/USERNAME" rather than ".../USERNAME".
            // Deactivated/deleted accounts have none of these — skip them.
            val rawValue = first["value"]?.jsonPrimitive?.contentOrNull()?.takeIf { it.isNotBlank() }
                ?: entryObject["title"]?.jsonPrimitive?.contentOrNull()?.takeIf { it.isNotBlank() }
                ?: usernameFromHref(first["href"]?.jsonPrimitive?.contentOrNull())
                ?: continue

            val ts = first["timestamp"]?.jsonPrimitive?.longOrNull
            val account = Account.of(rawValue, ts?.takeIf { it > 0 })
            // de-dupe, keep first occurrence (putIfAbsent is JVM-only, so do it by hand)
            if (account.username !in out) out[account.username] = account
        }
    }

    private fun usernameFromHref(href: String?): String? {
        if (href.isNullOrBlank()) return null
        return href.substringAfter("instagram.com/", "")
            .trim('/')
            .removePrefix("_u/")
            .trim('/')
            .ifBlank { null }
    }

    private fun kotlinx.serialization.json.JsonPrimitive.contentOrNull(): String? =
        if (isString) content else content.ifBlank { null }

    private fun looksLikeHtml(content: String): Boolean = content.trimStart().startsWith("<")

    /**
     * Every export entry is an `<a href="https://www.instagram.com/...">` link somewhere in the
     * document — selecting on that alone (rather than specific div classes, which aren't known and
     * are the part most likely to change) works for both real shapes: following.html's
     * username/blank/URL/date and followers_N.html's username/date with no visible URL line.
     */
    private fun collectHtmlEntries(content: String, out: MutableMap<String, Account>) {
        val anchors = Ksoup.parse(html = content).select("a[href*=instagram.com]")
        if (anchors.isEmpty()) throw ParseException("no instagram.com links found in HTML export")
        for (anchor in anchors) {
            val username = usernameFromHref(anchor.attr("href")) ?: continue
            val account = Account.of(username, timestampNearHtmlAnchor(anchor))
            if (account.username !in out) out[account.username] = account
        }
    }

    /**
     * Best-effort only: walks up a few ancestors looking for the confirmed real date format
     * ("Sep 17, 2026 11:21 am") and returns null rather than throwing if none is found, since the
     * exact markup nesting around each anchor isn't verified beyond the two real samples this was
     * built against.
     */
    private fun timestampNearHtmlAnchor(anchor: Element): Long? {
        var ancestor: Element? = anchor.parent()
        repeat(3) {
            val match = ancestor?.let { htmlDateRegex.find(it.text()) }
            if (match != null) return parseHtmlDate(match)
            ancestor = ancestor?.parent()
        }
        return null
    }

    private fun parseHtmlDate(match: MatchResult): Long? {
        val groups = match.groupValues
        val monthName = groups[1]
        val day = groups[2].toInt()
        val year = groups[3].toInt()
        val hour12 = groups[4].toInt()
        val minute = groups[5].toInt()
        val isPm = groups[6].equals("pm", ignoreCase = true)

        val month = htmlMonthAbbreviations.indexOfFirst { it.equals(monthName, ignoreCase = true) } + 1
        if (month == 0) return null
        val hour = when {
            !isPm && hour12 == 12 -> 0
            isPm && hour12 != 12 -> hour12 + 12
            else -> hour12
        }
        return try {
            LocalDateTime(year, month, day, hour, minute).toInstant(TimeZone.UTC).epochSeconds
        } catch (e: IllegalArgumentException) {
            null
        }
    }

    private companion object {
        val htmlDateRegex =
            Regex("""([A-Za-z]{3}) (\d{1,2}), (\d{4}) (\d{1,2}):(\d{2}) ([ap]m)""", RegexOption.IGNORE_CASE)
        val htmlMonthAbbreviations =
            listOf("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
        val htmlHeaderRegex = Regex("""^(Followers|Following)\s+Generated by\b""")
    }
}
